apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production  # Change as needed (dev, staging, prod)
data:
  DB_HOST: mysql-service
  DB_USER: root
  DB_PASSWORD: 1234
  DB_NAME: clothing_store
  JWT_SECRET: your_secret_key
