apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: production  # Change as needed (dev, staging, prod)
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: alishashaqiri/webstoreapplication-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "1234"
        - name: DB_NAME
          value: "clothing_store"
        - name: JWT_SECRET
          value: "your_secret_key"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: production  # Change as needed (dev, staging, prod)
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
