apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: production  # Change as needed (dev, staging, prod)
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: alishashaqiri/webstoreapplication-ui:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: production  # Change as needed (dev, staging, prod)
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
